import React, { createContext, useContext, useState } from "react";

const translations = {
  en: {
    title: "NovaCare Super Speciality Hospital",
    dashboard: "Dashboard",
    patients: "Patients",
    doctors: "Doctors",
    appointments: "Appointments",
    billing: "Billing",
    pharmacy: "Pharmacy",
    laboratory: "Laboratory",
    settings: "Settings",
    profile: "Profile",
    logout: "Logout",
    totalPatients: "Total Patients",
    activeSpecialists: "Active Specialists",
    revenueLogged: "Revenue Logged",
    todayAppointments: "Appointments Today",
    bedsCoordinator: "Live Beds & ICU Occupancy Coordinator",
    icuBeds: "ICU Beds (Intensive Care Unit)",
    generalBeds: "General Ward Beds",
    discharge: "Discharge Patient",
    admit: "Admit Patient",
    readyIntake: "Ready for intake",
    patientsRegistry: "Patient Records",
    addPatient: "+ Add Patient",
    searchPlaceholder: "Search records...",
    id: "ID",
    name: "Name",
    age: "Age",
    gender: "Gender",
    disease: "Disease",
    actions: "Actions",
    view: "View",
    edit: "Edit",
    delete: "Delete",
    conflictDetected: "Appointment Conflict: This doctor is already scheduled for an appointment at this date and time.",
    billingCalculator: "Automatic Invoice Calculator",
    consultationFee: "Consultation Fee (₹)",
    medicineCost: "Medicine Cost (₹)",
    labCharges: "Laboratory Charges (₹)",
    totalAmount: "Total Invoice Amount (₹)",
    username: "Username",
    password: "Password",
    signIn: "Sign In",
    signingIn: "Signing in...",
    createAccount: "Create an account",
    newUserRegistration: "New user registration?",
    patientTab: "Patient",
    staffTab: "Staff",
    adminTab: "Admin",
    loginTitle: "Login",
    enterCredentials: "Please enter your credentials to authenticate",
    forgetPassword: "Forgot Password?",
    patientPortalTagline: "Patient & User Portal",
    patientPortalDesc: "Sign in to access your personal dashboard, view prescription history, review lab laboratory test reports, schedule doctor appointments, and securely settle billing invoices online.",
    staffPortalTagline: "Doctor & Nurse Workstation",
    staffPortalDesc: "Sign in to manage patient diagnostics, view clinical appointment queues, update laboratory and pharmaceutical prescriptions, and coordinate shift rosters.",
    adminPortalTagline: "Hospital Admin Control Center",
    adminPortalDesc: "Manage system-wide configuration, access audits, register departments, assign doctors, control billing, and oversee overall hospital metrics."
  },
  ta: {
    title: "நோவாகேர் சூப்பர் ஸ்பெஷாலிட்டி மருத்துவமனை",
    dashboard: "டாஷ்போர்டு",
    patients: "நோயாளிகள்",
    doctors: "மருத்துவர்கள்",
    appointments: "சந்திப்புகள்",
    billing: "பில்லிங்",
    pharmacy: "மருந்தகம்",
    laboratory: "ஆய்வகம்",
    settings: "அமைப்புகள்",
    profile: "சுயவிவரம்",
    logout: "வெளியேறு",
    totalPatients: "மொத்த நோயாளிகள்",
    activeSpecialists: "செயலில் உள்ள நிபுணர்கள்",
    revenueLogged: "பதிவு செய்யப்பட்ட வருவாய்",
    todayAppointments: "இன்றைய சந்திப்புகள்",
    bedsCoordinator: "நேரடி படுக்கைகள் & ICU இருப்பு ஒருங்கிணைப்பாளர்",
    icuBeds: "ICU படுக்கைகள் (தீவிர சிகிச்சை பிரிவு)",
    generalBeds: "பொது வார்டு படுக்கைகள்",
    discharge: "டிஸ்சார்ஜ் செய்",
    admit: "நோயாளி அனுமதி",
    readyIntake: "அனுமதிக்கு தயார்",
    patientsRegistry: "நோயாளி பதிவுகள்",
    addPatient: "+ நோயாளி சேர்",
    searchPlaceholder: "பதிவுகளைத் தேடு...",
    id: "ஐடி (ID)",
    name: "பெயர்",
    age: "வயது",
    gender: "பாலினம்",
    disease: "நோய் / பாதிப்பு",
    actions: "செயல்கள்",
    view: "காண்",
    edit: "திருத்து",
    delete: "நீக்கு",
    conflictDetected: "அப்பாயிண்ட்மெண்ட் முரண்பாடு: இந்த மருத்துவர் ஏற்கனவே இந்த தேதி மற்றும் நேரத்தில் முன்பதிவு செய்யப்பட்டுள்ளார்.",
    billingCalculator: "தானியங்கி பில் கால்குலேட்டர்",
    consultationFee: "ஆலோசனை கட்டணம் (₹)",
    medicineCost: "மருந்து கட்டணம் (₹)",
    labCharges: "ஆய்வக கட்டணம் (₹)",
    totalAmount: "மொத்த பில் தொகை (₹)",
    username: "பயனர் பெயர்",
    password: "கடவுச்சொல்",
    signIn: "உள்நுழை",
    signingIn: "உள்நுழைகிறது...",
    createAccount: "கணக்கை உருவாக்கு",
    newUserRegistration: "புதிய பயனர் பதிவா?",
    patientTab: "நோயாளி",
    staffTab: "பணியாளர்கள்",
    adminTab: "நிர்வாகி",
    loginTitle: "உள்நுழைவு",
    enterCredentials: "அங்கீகரிக்க உங்கள் விவரங்களை உள்ளிடவும்",
    forgetPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    patientPortalTagline: "நோயாளி & பயனர் போர்டல்",
    patientPortalDesc: "உங்கள் தனிப்பட்ட டாஷ்போர்டை அணுகவும், மருந்துச்சீட்டு வரலாற்றைப் பார்க்கவும், ஆய்வக சோதனை அறிக்கைகளை மதிப்பாய்வு செய்யவும், மருத்துவ சந்திப்புகளை திட்டமிடவும் மற்றும் பில்களை செலுத்தவும் உள்நுழையவும்.",
    staffPortalTagline: "மருத்துவர் & செவிலியர் பணிநிலையம்",
    staffPortalDesc: "நோயாளி கண்டறிதல்களை நிர்வகிக்கவும், சந்திப்பு வரிசைகளைப் பார்க்கவும், மருந்துச்சீட்டுகளைப் புதுப்பிக்கவும் மற்றும் ஷிஃப்டுகளை ஒருங்கிணைக்கவும் உள்நுழையவும்.",
    adminPortalTagline: "மருத்துவமனை நிர்வாக கட்டுப்பாட்டு மையம்",
    adminPortalDesc: "அமைப்பு ரீதியான உள்ளமைவை நிர்வகிக்கவும், தணிக்கைகளை அணுகவும், துறைகளைப் பதிவு செய்யவும், மருத்துவர்களை நியமிக்கவும், பில்லிங்கைக் கட்டுப்படுத்தவும் மற்றும் மருத்துவமனை அளவீடுகளைக் கண்காணிக்கவும்."
  },
  hi: {
    title: "नोवाकेयर सुपर स्पेशलिटी अस्पताल",
    dashboard: "डैशबोर्ड",
    patients: "मरीज़",
    doctors: "डॉक्टर",
    appointments: "नियुक्तियां",
    billing: "बिलिंग",
    pharmacy: "फार्मेसी",
    laboratory: "प्रयोगशाला",
    settings: "सेटिंग्स",
    profile: "प्रोफ़ाइल",
    logout: "लॉगआउट",
    totalPatients: "कुल मरीज़",
    activeSpecialists: "सक्रिय विशेषज्ञ",
    revenueLogged: "दर्ज राजस्व",
    todayAppointments: "आज की नियुक्तियां",
    bedsCoordinator: "लाइव बेड और आईसीयू उपलब्धता समन्वयक",
    icuBeds: "आईसीयू बेड (सघन चिकित्सा इकाई)",
    generalBeds: "सामान्य वार्ड बेड",
    discharge: "मरीज़ डिस्चार्ज करें",
    admit: "मरीज़ भर्ती करें",
    readyIntake: "प्रवेश के लिए तैयार",
    patientsRegistry: "मरीज़ रिकॉर्ड",
    addPatient: "+ मरीज़ जोड़ें",
    searchPlaceholder: "रिकॉर्ड खोजें...",
    id: "आईडी (ID)",
    name: "नाम",
    age: "उम्र",
    gender: "लिंग",
    disease: "बीमारी / रोग",
    actions: "कार्रवाई",
    view: "देखें",
    edit: "संपादित करें",
    delete: "हटाएं",
    conflictDetected: "नियुक्ति संघर्ष: इस डॉक्टर के पास पहले से ही इस तिथि और समय पर नियुक्ति है।",
    billingCalculator: "स्वचालित चालान कैलकुलेटर",
    consultationFee: "परामर्श शुल्क (₹)",
    medicineCost: "दवा लागत (₹)",
    labCharges: "प्रयोगशाला शुल्क (₹)",
    totalAmount: "कुल चालान राशि (₹)",
    username: "यूज़रनेम",
    password: "पासवर्ड",
    signIn: "साइन इन",
    signingIn: "साइन इन हो रहा है...",
    createAccount: "खाता बनाएं",
    newUserRegistration: "नया उपयोगकर्ता पंजीकरण?",
    patientTab: "मरीज़",
    staffTab: "कर्मचारी",
    adminTab: "एडमिन",
    loginTitle: "लॉगिन",
    enterCredentials: "सत्यापित करने के लिए कृपया अपनी साख दर्ज करें",
    forgetPassword: "पासवर्ड भूल गए?",
    patientPortalTagline: "मरीज़ और उपयोगकर्ता पोर्टल",
    patientPortalDesc: "अपने व्यक्तिगत डैशबोर्ड तक पहुँचने, नुस्खे के इतिहास को देखने, प्रयोगशाला परीक्षण रिपोर्ट की समीक्षा करने, डॉक्टर की नियुक्तियों को निर्धारित करने और बिलों का भुगतान करने के लिए साइन इन करें।",
    staffPortalTagline: "डॉक्टर और नर्स वर्कस्टेशन",
    staffPortalDesc: "मरीज़ों के निदान का प्रबंधन करने, क्लिनिकल अपॉइंटमेंट कतार देखने, नुस्खे को अपडेट करने और पारियों का समन्वय करने के लिए साइन इन करें।",
    adminPortalTagline: "अस्पताल व्यवस्थापक नियंत्रण केंद्र",
    adminPortalDesc: "सिस्टम-व्यापी कॉन्फ़िगरेशन प्रबंधित करें, ऑडिट तक पहुंचें, विभागों को पंजीकृत करें, डॉक्टरों को नियुक्त करें, बिलिंग को नियंत्रित करें और समग्र अस्पताल मेट्रिक्स की निगरानी करें।"
  },
  te: {
    title: "నోవాకేర్ సూపర్ స్పెషాలిటీ హాస్పిటల్",
    dashboard: "డాష్‌బోర్డ్",
    patients: "రోగులు",
    doctors: "వైద్యులు",
    appointments: "అపాయింట్‌మెంట్‌లు",
    billing: "బిల్లింగ్",
    pharmacy: "ఫార్మసీ",
    laboratory: "లాబొరేటరీ",
    settings: "సెట్టింగులు",
    profile: "ప్రొఫೈల్",
    logout: "లాగ్అవుట్",
    totalPatients: "మొత్తం రోగులు",
    activeSpecialists: "యాక్టివ్ నిపుణులు",
    revenueLogged: "నమోదైన ఆదాయం",
    todayAppointments: "నేటి అపాయింట్‌మెంట్‌లు",
    bedsCoordinator: "లైవ్ బెడ్స్ & ICU లభ్యత సమన్వయకర్త",
    icuBeds: "ICU బెడ్స్ (తీవ్ర చికిత్స విభాగం)",
    generalBeds: "జనరల్ వార్డ్ బెడ్స్",
    discharge: "డిశ్చార్జ్ చేయి",
    admit: "రోగిని చేర్చుకో",
    readyIntake: "చేరికకు సిద్ధంగా ఉంది",
    patientsRegistry: "రోಗಿ రికార్డులు",
    addPatient: "+ రోగిని చేర్చు",
    searchPlaceholder: "రికార్డులను వెతకండి...",
    id: "ఐడీ (ID)",
    name: "పేరు",
    age: "వయస్సు",
    gender: "లింగం",
    disease: "వ్యాధి / రోగం",
    actions: "చర్యలు",
    view: "చూడు",
    edit: "సవరించు",
    delete: "తొలగించు",
    conflictDetected: "అపాయింట్‌మెంట్ వివాదం: ఈ వైద్యుడు ఇప్పటికే ఈ తేదీ మరియు సమయంలో బుక్ చేయబడ్డారు.",
    billingCalculator: "ఆటోమేటిక్ ఇన్వాయిస్ కాలిక్యులేటర్",
    consultationFee: "కన్సల్టేషన్ ఫీజు (₹)",
    medicineCost: "మందుల ఖర్చు (₹)",
    labCharges: "ల్యాబ్ ఛార్జీలు (₹)",
    totalAmount: "మొత్తం ఇన్వాయిస్ మొత్తం (₹)",
    username: "వినియోగదారు పేరు (Username)",
    password: "పాస్‌వర్డ్ (Password)",
    signIn: "సైన్ ఇన్",
    signingIn: "సైన్ ఇన్ అవుతోంది...",
    createAccount: "ఖాతాను సృష్టించండి",
    newUserRegistration: "కొత్త యూజర్ రిజిస్ట్రేషన్?",
    patientTab: "రోగి",
    staffTab: "సిబ్బంది",
    adminTab: "అడ్మిన్",
    loginTitle: "లాగిన్",
    enterCredentials: "ధృవీకరించడానికి దయచేసి మీ వివరాలను నమోదు చేయండి",
    forgetPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    patientPortalTagline: "రోగులు & యూజర్ పోర్టల్",
    patientPortalDesc: "మీ వ్యక్తిగత డాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి, ప్రిస్క్రిప్షన్ చరిత్రను చూడటానికి, ల్యాబ్ నివేదికలను సమీక్షించడానికి, వైద్యుల అపాయింట్‌మెంట్‌లను షెడ్యూల్ చేయడానికి మరియు బిల్లులను చెల్లించడానికి సైన్ ఇన్ చేయండి.",
    staffPortalTagline: "వైద్యుడు & నర్సు వర్క్‌స్టేషన్",
    staffPortalDesc: "రోగుల నిర్ధారణలను నిర్వహించడానికి, అపాయింట్‌మెంట్ క్యూలను చూడటానికి, ప్రిస్క్రిప్షన్‌లను నవీకరించడానికి మరియు షిఫ్టులను సమన్వయం చేయడానికి సైన్ ఇన్ చేయండి.",
    adminPortalTagline: "హాస్పిటల్ అడ్మిన్ కంట్రోల్ సెంటర్",
    adminPortalDesc: "సిస్టమ్-వ్యాప్త కాన్ఫిగరేషన్‌ను నిర్వహించండి, ఆడిట్‌లను యాక్సెస్ చేయండి, విభాగాలను నమోదు చేయండి, వైద్యులను కేటాయించండి, బిల్లింగ్‌ను నియంత్రించండి మరియు మొత్తం ఆసుపత్రి కొలతలను పర్యవేక్షించండి."
  },
  kn: {
    title: "ನೋವಾಕೇರ್ ಸೂಪರ್ ಸ್ಪೆಷಾಲಿಟಿ ಆಸ್ಪತ್ರೆ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    patients: "ರೋಗಿಗಳು",
    doctors: "ವೈದ್ಯರು",
    appointments: "ನೇಮಕಾತಿಗಳು",
    billing: "ಬಿಲ್ಲಿಂಗ್",
    pharmacy: "ಫಾರ್ಮಸಿ",
    laboratory: "ಪ್ರಯೋಗಾಲಯ",
    settings: "ಸಂಯೋಜನೆಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    logout: "ಲಾಗ್ ಔಟ್",
    totalPatients: "ಒಟ್ಟು ರೋಗಿಗಳು",
    activeSpecialists: "ಸಕ್ರಿಯ ತಜ್ಞರು",
    revenueLogged: "ದಾಖಲಾದ ಆದಾಯ",
    todayAppointments: "ಇಂದಿನ ನೇಮಕಾತಿಗಳು",
    bedsCoordinator: "ಲೈವ್ ಬೆಡ್ಸ್ ಮತ್ತು ಐಸಿಯು ಲಭ್ಯತೆ ಸಂಯೋಜಕ",
    icuBeds: "ಐಸಿಯು ಬೆಡ್ಸ್ (ತೀವ್ರ ನಿಗಾ ಘಟಕ)",
    generalBeds: "ಜನರಲ್ ವಾರ್ಡ್ ಬೆಡ್ಸ್",
    discharge: "ಡಿಸ್ಚಾರ್ಜ್ ಮಾಡಿ",
    admit: "ರೋಗಿ ಸೇರಿಸು",
    readyIntake: "ಪ್ರವೇಶಕ್ಕೆ ಸಿದ್ಧವಾಗಿದೆ",
    patientsRegistry: "ರೋಗಿಗಳ ದಾಖಲೆಗಳು",
    addPatient: "+ ರೋಗಿಯನ್ನು ಸೇರಿಸಿ",
    searchPlaceholder: "ದಾಖಲೆಗಳನ್ನು ಹುಡುಕಿ...",
    id: "ಐಡಿ (ID)",
    name: "ಹೆಸರು",
    age: "ವಯಸ್ಸು",
    gender: "ಲಿಂಗ",
    disease: "ಕಾಯಿಲೆ / ರೋಗ",
    actions: "ಕ್ರಮಗಳು",
    view: "ನೋಡಿ",
    edit: "ಬದಲಾಯಿಸಿ",
    delete: "ಅಳಿಸಿ",
    conflictDetected: "ನೇಮಕಾತಿ ಸಂಘರ್ಷ: ಈ ವೈದ್ಯರು ಈಗಾಗಲೇ ಈ ದಿನಾಂಕ ಮತ್ತು ಸಮಯದಲ್ಲಿ ನೇಮಕಾತಿ ಹೊಂದಿದ್ದಾರೆ.",
    billingCalculator: "ಸ್ವಯಂಚಾಲಿತ ಸರಕುಪಟ್ಟಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    consultationFee: "ಸಮಾಲೋಚನೆ ಶುಲ್ಕ (₹)",
    medicineCost: "ಔಷಧಿ ವೆಚ್ಚ (₹)",
    labCharges: "ಪ್ರಯೋಗಾಲಯ ಶುಲ್ಕಗಳು (₹)",
    totalAmount: "ಒಟ್ಟು ಸರಕುಪಟ್ಟಿ ಮೊತ್ತ (₹)",
    username: "ಬಳಕೆದಾರ ಹೆಸರು (Username)",
    password: "ಪಾಸ್‌ವರ್ಡ್ (Password)",
    signIn: "ಸೈನ್ ಇನ್",
    signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    newUserRegistration: "ಹೊಸ ಬಳಕೆದಾರ ನೋಂದಣಿ?",
    patientTab: "ರೋಗಿ",
    staffTab: "ಸಿಬ್ಬಂದಿ",
    adminTab: "ಅಡ್ಮಿನ್",
    loginTitle: "ಲಾಗಿನ್",
    enterCredentials: "ದೃಢೀಕರಿಸಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
    forgetPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    patientPortalTagline: "ರೋಗಿ ಮತ್ತು ಬಳಕೆದಾರರ ಪೋರ್ಟಲ್",
    patientPortalDesc: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಲು, ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಇತಿಹಾಸವನ್ನು ವೀಕ್ಷಿಸಲು, ಲ್ಯಾಬ್ ವರದಿಗಳನ್ನು ಪರಿಶೀಲಿಸಲು, ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳನ್ನು ನಿಗದಿಪಡಿಸಲು ಮತ್ತು ಬಿಲ್‌ಗಳನ್ನು ಪಾವತಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    staffPortalTagline: "ವೈದ್ಯರು ಮತ್ತು ದಾದಿಯರ ವರ್ಕ್‌ಸ್ಟೇಷನ್",
    staffPortalDesc: "ರೋಗಿಗಳ ರೋಗನಿರ್ಣಯವನ್ನು ನಿರ್ವಹಿಸಲು, ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಸರತಿ ಸಾಲುಗಳನ್ನು ವೀಕ್ಷಿಸಲು, ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳನ್ನು ನವೀಕರಿಸಲು ಮತ್ತು ಶಿಫ್ಟ್‌ಗಳನ್ನು ಸಂಘಟಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    adminPortalTagline: "ಆಸ್ಪತ್ರೆ ನಿರ್ವಾಹಕರ ನಿಯಂತ್ರಣ ಕೇಂದ್ರ",
    adminPortalDesc: "ಸಿಸ್ಟಮ್-ವ್ಯಾಪಕ ಸಂರಚನೆಯನ್ನು ನಿರ್ವಹಿಸಿ, ಆಡಿಟ್‌ಗಳನ್ನು ಪ್ರವೇಶಿಸಿ, ಇಲಾಖೆಗಳನ್ನು ನೋಂದಾಯಿಸಿ, ವೈದ್ಯರನ್ನು ನಿಯೋಜಿಸಿ, ಬಿಲ್ಲಿಂಗ್ ನಿಯಂತ್ರಿಸಿ ಮತ್ತು ಒಟ್ಟಾರೆ ಆಸ್ಪತ್ರೆಯ ಮೆಟ್ರಿಕ್‌ಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ."
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("hims_lang") || "en";
  });

  const t = (key) => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem("hims_lang", lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
